export const fortunes = [
	'A surprising event awaits you.',
	'Change is on the horizon.',
	'Trust your instincts in the coming days.',
	'An opportunity will present itself soon.',
	'Someone from your past will resurface.',
	'A decision will prove significant.',
	'The path ahead holds mystery.',
	'Fortune favors your next bold move.',
	'A door closes, but another opens.',
	'Your patience will be rewarded.',
	'Look beyond the obvious choice.',
	'The stars align in your favor.',
	'A journey begins with small steps.',
	'Time reveals hidden truths.',
	'An unexpected alliance forms.',
	'What seems lost will return.',
	'Trust in the natural flow.',
	'A cycle completes itself.',
	'Wisdom comes from unlikely sources.',
	'The answer is closer than you think.',
	'A pattern emerges from chaos.',
	'Tomorrow brings fresh perspective.',
	'Listen to the quiet voice within.',
	'A genuine smile opens many doors.',
	'The wind shifts in your favor.',
	'Ancient wisdom guides your path.',
	'Simple choices yield profound results.',
	'A friend becomes something more.',
	'Messages arrive in strange ways.',
	'Your efforts bear unexpected fruit.',
	'The past holds valuable lessons.',
	'A dream becomes reality.',
	'Silence speaks volumes.',
	'Trust the timing of events.',
	'A mystery solves itself.',
	'Fortune favors the patient.',
	'Hidden talents emerge.',
	'The clouds part to reveal truth.',
	'A small gift carries great meaning.',
	'The impossible becomes possible.',
	'Destiny takes an unusual turn.',
	'What you seek seeks you.',
	'A humble beginning leads to greatness.',
	'The answer lies in balance.',
	'Time heals all doubts.',
	'A cryptic message brings clarity.',
	'The universe conspires to help you.',
	'A chance encounter changes everything.',
	'Look beneath the surface.',
	'The pieces fall into place.',
	'A secret comes to light.',
	'The wheel of fortune turns.',
	'A new chapter begins.',
	'Trust in perfect timing.',
	'Wisdom comes through waiting.',
	'A butterfly effect takes hold.',
	'The truth reveals itself.',
	'A pattern completes itself.',
	'Fortune favors the prepared.',
	'The obvious path misleads.',
	'A subtle sign points the way.',
	'The unexpected brings joy.',
	'A riddle finds its answer.',
	'Time is your ally.',
	'The stars whisper secrets.',
	'A circle closes.',
	'The maze has an exit.',
	'Patience reveals the path.',
	'A mystery contains a gift.',
	'The fog will lift.',
	'Signs point to success.',
	'A door opens within.',
	'The cosmos aligns.',
	'Truth hides in plain sight.',
	'A seed of hope grows.',
	'The wind knows the way.',
	'Silence holds answers.',
	'A bridge appears.',
	'The path winds forward.',
	'Fortune smiles mysteriously.',
	'A key finds its lock.',
	'The puzzle solves itself.',
	'Destiny plays its hand.',
	'A shadow reveals light.',
	'The river knows its course.',
	'Time unveils all.',
	'A message finds you.',
	'The clouds have silver linings.',
	'A paradox resolves itself.',
	'The mirror shows truth.',
	'A cycle renews.',
	'The labyrinth guides you.',
	'Fortune favors the bold.',
	'A sign appears.',
	'The mist parts.',
	'Wisdom comes in whispers.',
	'A pattern emerges.',
	'The road reveals itself.',
	'Trust the journey.',
	'A secret becomes known.',
	'The tide turns.',
	'Time tells all.',
	'A mystery unfolds.',
	'The way becomes clear.',
	'Fortune finds you.',
];
